---
- name: Configure VPC
  hosts: distribution
  connection: local
  gather_facts: false

  tasks:
    - name: Enable Features
      with_items:
        - hsrp
      nxos_feature:
        provider:
          host: "{{inventory_hostname}}"
          transport: nxapi
          timeout: 15
        feature: "{{ item }}"
        state: enabled

    - name: Configure HSRP
      with_items: "{{ hsrp_interfaces }}"
      nxos_hsrp:
        provider:
          host: "{{inventory_hostname}}"
          transport: nxapi
          timeout: 15
        group: "{{ item.group }}"
        vip: "{{ item.vip }}"
        interface: "{{ item.interface }}"