---
- name: Generate Configuration from Template
  hosts: localhost
  gather_facts: no
  vars_files:
    - example3_vars.yaml

  tasks: 
    - name: "Generate config"
      template: 
        src: "bgp_config.j2"
        dest: "./{{ item.router }}_bgp.cfg"
      with_items: '{{ core_routers }}'